-- V001__create_tables.sql

-- Таблица product
CREATE TABLE public.product (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    picture_url character varying(255)
);

-- Таблица product_info
CREATE TABLE public.product_info (
    product_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    price double precision
);

-- Таблица orders
CREATE TABLE public.orders (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    status character varying(255)
);

-- Таблица orders_date
CREATE TABLE public.orders_date (
    order_id bigint NOT NULL,
    status character varying(255),
    date_created date DEFAULT CURRENT_DATE
);

-- Таблица order_product
CREATE TABLE public.order_product (
    quantity integer NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL
);