name: Main workflow
on:
  push:
    branches:
      - main
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Flyway Migration
        run: |
          # Загрузка Flyway Command-line
          wget -qO flyway.tar.gz https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.5.13/flyway-commandline-8.5.13-linux-x64.tar.gz
          tar -xzf flyway.tar.gz
          # Запуск миграций к базе данных "store"
          ./flyway-8.5.13/flyway -url="jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/store" -user="${{ secrets.DB_USER }}" -password="${{ secrets.DB_PASSWORD }}" migrate

      - name: Download and setup autotests binaries
        run: |
          wget -qO- cloud-services-engineer.gitlab.yandexcloud.net/practicum-cloud-services/dbops-autotests/-/package_files/1/download > dbopstest
          chmod +x ./dbopstest
          mv ./dbopstest /usr/local/bin/dbopstest

      - name: Test
        run: |
          dbopstest \
            -test.v \
            -host=${{ secrets.DB_HOST }} \
            -port=${{ secrets.DB_PORT }} \
            -user=${{ secrets.DB_USER }} \
            -password=${{ secrets.DB_PASSWORD }} \
            -db=${{ secrets.DB_NAME }}